### PR TITLE
Spelling, damnit

### PR DESCRIPTION
**Pull request by SudoSisyphus**

### CODE REVIEW

**Comment by ArielH25** [comment]
er no this is correct spelling in uk

**Comment by TheDevMinerTV** [comment]
LOL, okay

**Comment by nathan-www** [comment]
lol!
Spelling mistake? 
Ok, let's change all the class names and break the css and js associated with those elements!

**Comment by TheDevMinerTV** [comment]
sure lol

**Comment by TheDevMinerTV** [comment]
jk jk, this pull request is closed btw

**Comment by nathan-www** [comment]
ik, it's just funny

**Pull request closed without merging**
